"""initial schema

Revision ID: 24f0a459bdfe
Revises: 
Create Date: 2026-07-06 16:43:15.641033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f0a459bdfe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('icon_hash', sa.String(length=64), nullable=True),
    sa.Column('installed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('enabled_modules', sa.JSON(), nullable=False),
    sa.Column('mod_role_ids', sa.JSON(), nullable=False),
    sa.Column('mod_alert_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('burst_window_seconds', sa.Integer(), nullable=True),
    sa.Column('burst_channel_threshold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('burst_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('channel_ids_hit', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('window_expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_burst_windows_guild_id'), 'burst_windows', ['guild_id'], unique=False)
    op.create_index('ix_burst_windows_lookup', 'burst_windows', ['guild_id', 'user_id', 'content_hash'], unique=False)
    op.create_index(op.f('ix_burst_windows_user_id'), 'burst_windows', ['user_id'], unique=False)
    op.create_index(op.f('ix_burst_windows_window_expires_at'), 'burst_windows', ['window_expires_at'], unique=False)
    op.create_table('mod_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=False),
    sa.Column('matched_pattern', sa.String(length=30), nullable=False),
    sa.Column('channel_ids', sa.JSON(), nullable=False),
    sa.Column('message_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mod_actions_created_at'), 'mod_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_mod_actions_guild_id'), 'mod_actions', ['guild_id'], unique=False)
    op.create_table('scam_image_hashes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('phash', sa.String(length=64), nullable=False),
    sa.Column('source_incident_id', sa.Integer(), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.guild_id'], ),
    sa.ForeignKeyConstraint(['source_incident_id'], ['mod_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scam_image_hashes_guild_id'), 'scam_image_hashes', ['guild_id'], unique=False)
    op.create_index(op.f('ix_scam_image_hashes_phash'), 'scam_image_hashes', ['phash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scam_image_hashes_phash'), table_name='scam_image_hashes')
    op.drop_index(op.f('ix_scam_image_hashes_guild_id'), table_name='scam_image_hashes')
    op.drop_table('scam_image_hashes')
    op.drop_index(op.f('ix_mod_actions_guild_id'), table_name='mod_actions')
    op.drop_index(op.f('ix_mod_actions_created_at'), table_name='mod_actions')
    op.drop_table('mod_actions')
    op.drop_index(op.f('ix_burst_windows_window_expires_at'), table_name='burst_windows')
    op.drop_index(op.f('ix_burst_windows_user_id'), table_name='burst_windows')
    op.drop_index('ix_burst_windows_lookup', table_name='burst_windows')
    op.drop_index(op.f('ix_burst_windows_guild_id'), table_name='burst_windows')
    op.drop_table('burst_windows')
    op.drop_table('guilds')
    # ### end Alembic commands ###
